name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # 🔎 Step tambahan untuk cek secret
      - name: Check if EXPO_TOKEN exists
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "❌ EXPO_TOKEN is NOT set"
            exit 1
          else
            echo "✅ EXPO_TOKEN is set"
          fi

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Android on EAS (wait until done)
        run: eas build --platform android --profile preview --non-interactive
